config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :posts do
    member do
      get 'follow', to: 'posts#follow'
      get 'unfollow', to: 'posts#unfollow'
    end
    resources :comments, only: [:create]
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :followships, foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :followships, source: :follower

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save!
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    authorize @post
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @post
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  def follow
    @post = Post.find(params[:id])
    current_user.follow(@post)
    respond_to do |format|
      format.html { redirect_to @post}
      format.js
    end
  end

  def unfollow
    @post = Post.find(params[:id])
    current_user.unfollow(@post)
    respond_to do |format|
      format.html {redirect_to @post}
      format.js
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/views/posts/_follow_link.html.erb
<%= link_to 'Follow', follow_post_path(@post), remote: true, id: 'follow-link', data: { type: :json }, class: 'btn btn--primary' %>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title, required: true %>
  
  <%= form.label :content %>
  <%= form.text_area :content, required: true %>
  
  <%= form.submit class: 'btn btn--secondary' %>
<% end %>

app/views/posts/_unfollow_link.html.erb
<%= link_to 'Unfollow', unfollow_post_path(@post), id: 'follow-link' ,class: 'btn btn--primary' %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>
<%= link_to 'Show', @post,class: 'btn btn--dark' %>
<%= link_to 'Back to Posts', posts_path, class: 'btn btn--light' %>

app/views/posts/index.html.erb
<div class="posts-container">
  <h1 class="posts-heading">All Posts</h1>
  <table class="posts-table">
    <thead>
      <tr>
        <th>Title</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= link_to post.title, post, class: "post-link" %></td>
          <% if policy(post).update? %>
          <td><%= link_to 'Edit', edit_post_path(post), class: "edit-post-link btn btn--light" %></td>
          <% end %>
          <% if policy(post).destroy? %>
          <td>
            <%= form_for(post, method: :delete, data: { }) do |f| %>
              <%= f.submit 'Delete', class: " btn btn--primary" %>
            <% end %>
          </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New Post', new_post_path, class: "new-post-link" %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>
<%= link_to 'Back to Posts', posts_path, class: 'btn btn--light' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>

<h3>Actions:</h3>
<% if user_signed_in? %>
  <% if current_user.following?(@post) %>
    <%= render 'posts/unfollow_link' %>
  <% else %>
    <%= render 'posts/follow_link' %>
  <% end %>
<% end %>

<h2>Comments:</h2>
<ul>
  <% @post.comments.each do |comment| %>
    <li id="comment-<%= comment.id %>">
      <%= comment.content %>
    </li>
  <% end %>
</ul>

<h3>Add a Comment:</h3>
<%= render 'comments/form', comment: @comment %>

<h3>Users Who Follow This Post:</h3>
<ul>
  <% @post.followers.each do |follower| %>
    <li><%= follower.name %></li>
  <% end %>
</ul>
<% if policy(@post).update? %>
<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn--dark' %>
<% end %>
<%= link_to 'Back to Posts', posts_path, class: 'btn btn--light' %>